### ISSUE TITLE
Client document list

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#100]
Hi

I t would be great to add "Clients" to the overview of the main page (Documents, Timeline and Catalogs).
For me it's easier to search for documents under the name of the clients instead of the timeline for example.

Edit:
Actually, the timeline is good, but maybe the names of the customers before the year could be listed?

**Comment by dragotin** [comment]
It is there:
![ksnip_20210409-124239](https://user-images.githubusercontent.com/1070214/114168886-2b125100-9931-11eb-91d4-274a08b55c06.png)

Maybe you do not see the column because it is scrolled out to the right? Or very slim?
You can move the columns in the order you want.

**Comment by DanSman** [comment]
I thought of something more like this.

![cleints](https://user-images.githubusercontent.com/28892085/114254492-c2e06f80-9a03-11eb-8df7-a8f06a03edca.png)
