### ISSUE TITLE
Not working: Fix line breaking method for Weasyprint. 

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#104]
I'm just trying to use weasyprint instead but the fix https://github.com/dragotin/kraft/commit/72deccc3875071d186075d133eddbd07818ace07 doesn't work for me. It's still in one line.

**Comment by dragotin** [comment]
Please make sure that your report template file contains 
```
{% autoescape off %}
```
It has been `on` before, but must be off to make the multiline work.

Also 
```
{{ item.text }}
```
needs to be changed to 
```
{{ item.htmlText }}
```
Please check and let me know.

**Comment by DanSman** [comment]
Thanks!
It works.
