### ISSUE TITLE
Add "sortKey" option in GUI

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#107]
I'm organizing everything in the database myself right now. The most frequently used folders and templates are moved on top of my list.

That would be easier to have the option in the GUI itself.

**Comment by dragotin** [comment]
Talking about template catalogues: Within a folder templates can be ordered manually in the GUI by dragging them around. 

But I realize that dragging around does not work properly for folders on top level.

**Comment by DanSman** [comment]
Yes, it is a little tricky, especially for templates. Folders are "easy" in the database, but templates are tricky. 
Just adding one folder by creating a new document with all templates ordered is great!

**Comment by dragotin** [comment]
Sorting works fine now.
