### ISSUE TITLE
Two releases named "Gunny". ;)

### ISSUE THREAD

**Issue by bernhardreiter** [dragotin/kraft#109]
https://volle-kraft-voraus.de/Main/Releases

> Kraft Release 0.96 - release name Gunny

> Kraft Release 0.95 - release name Gunny

But `Jupp` and `Rio` had been there several times as well. 
Just wanted to point it out, as it strikes me as odd, just like the version number, I guess it should have been 1.0 long ago, because some people use it in production.  (Thanks for doing Free Software.) ;)

**Comment by dragotin** [comment]
Yes, that is totally intentional :-) I like to use the release names for a little series of releases.
Thanks for reporting. And yes, 1.0 will be coming...
