### ISSUE TITLE
Icon Kuddlmuddl

### ISSUE THREAD

**Issue by dragotin** [dragotin/kraft#11]
The Kraft specific icons should be in the resource file, the others taken from the theme. Currently the cmake installing is not clean.

**Comment by dragotin** [comment]
Also, add Documents- and Timeline icon to the resource pack.

**Comment by dragotin** [comment]
Icons to resource: 97d3fde991d3fb7538f5cd6ae509f2534c528222

**Comment by dragotin** [comment]
might be fixed by #32. Check!

**Comment by dragotin** [comment]
Also double check the use of icons: Some are duplicates, such as the Document - create icons. @moini

**Comment by Moini** [comment]
Thanks for tackling this.

I'm now using the self-built version, and icons still look a bit off in the preferences (different sizes), as well as in the main button row (all identical):

![grafik](https://user-images.githubusercontent.com/3240233/141700924-5eff750c-0a6b-405e-afd0-450a46601fcb.png)

The icons in the document edit dialog look alright in my build:

![grafik](https://user-images.githubusercontent.com/3240233/141700986-43f067ca-f484-4b39-be18-6a381efe0bf4.png)

Disclaimer: did not try the AppImage. Should I? I'd rather wait until the icons work okay in one place before we move to the next.

**Comment by dragotin** [comment]
Icons can either come from the system "theme" (ie. the icons installed on the system) or be bundled with the app. No standard linux distro icon set contains all the icons Kraft would need, or with the correct size. That is the reason for the small icons you see. 

So at some point I started to put icons into the app bundle, but not all have been handled there. I can not draw icons myself, and also have a hard time to look for icons.

The ideal solution would be to find an icon set that provides all icons Kraft needs. Maybe you want to help?

The three identical icons are indeed correct, as I used the same one for all three "create" actions. I will try to find a better solution.

**Comment by dragotin** [comment]
Fixed duplicate icons with d7406c2c919ebcfee202e6d3d6e67a52557fe97d

Another aspect here: I am picking the icons from the KDE theme (breeze). Users who run the app on other desktops might miss icons that are not in their set. Sigh.

**Comment by Moini** [comment]
The previous duplicates are distinguishable now, thank you!

The copy icon is a bit unusual - it looks more like it were a dissolving document in my installation - is that intended?
![grafik](https://user-images.githubusercontent.com/3240233/142935606-dd8cc194-d4ef-4148-853d-6106eebee43d.png)

Sure, I think I'd be able to find some icons for you. I'm not familiar with Qt/KDE icon handling, only know how to create gtk-compatible icon sets, as in https://gitlab.com/inkscape/inkscape/-/tree/master/share/icons/hicolor - is it the same principle?

**Comment by dragotin** [comment]
Sorry for getting back late on this.

Yes, same principle. SVG is great. It makes probably sense if, at some point, Kraft has all icons that it needs in it's own resources, rather than taking from the window managers theme. if you could help with that, I'd be really grateful.

**Comment by Moini** [comment]
Okay - schau ich mir frühestens gegen Monatsende an, aber das sollte ja auch noch reichen. Frohes Neues Jahr, @dragotin!

**Comment by dragotin** [comment]
Es reicht wann immer du Zeit dafür aufbringen magst :-) Happy new Year!

**Comment by dragotin** [comment]
Obsoleted by #175
