### ISSUE TITLE
Apply the global hourly rate

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#110]
I just need more information about it. I can't find any info about it. I think I even asked the question already but I've forgotten.

What does it do when I mark it? Where can I set the global hourly rate?

**Comment by dragotin** [comment]
Oh yes. The idea is that every document can have "global" rates, which are used in calculated templates instead of the ones that were there when the  calculation was done.

This feature was not yet implemented, but the checkbox is still there.

**Comment by dragotin** [comment]
![ksnip_20210510-213653](https://user-images.githubusercontent.com/1070214/117714963-f1ef2a00-b1d7-11eb-9177-c2ca257920fe.png)
