### ISSUE TITLE
mariadb update v.10.6.3 - 1.1.2000 date

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#112]
Hi

I'm not really sure it's the new versions of mariadb or not tbh.
But since the last update it seems to have some issues with database. Some invoices etc got a 1.1.2000 date. Also all creation date and last modifications are gone. 

I haven't done anything else. Just a server update. So like I mentioned I'm not really sure. 
It seems that the dates are no longer stored.

Edit:
I downgraded mariadb back to the v.10.5.11. Now its working again. 

BTW I did run `mariadb-upgrade -u root -p` but this didn't change anything.

**Comment by dragotin** [comment]
Probably related: https://bugs.kde.org/show_bug.cgi?id=439769

**Comment by dragotin** [comment]
It is fixed in Qt: https://codereview.qt-project.org/c/qt/qtbase/+/363880

**Comment by DanSman** [comment]
Hi

I've just updated everything. I'm on versions:
```
mariadb 10.6.4-1
kraft 0.97-1
```

Everything seems to work now.
