### ISSUE TITLE
Lots of identical and missing icons in AppImage

### ISSUE THREAD

**Issue by Moini** [dragotin/kraft#119]
Hi,
I just downloaded kraft-0.97-lp151.39.1.Build14.82.glibc2.25-x86_64.AppImage
and found that:

* there are many identical icons, making it impossible to discern the buttons
* many icons seem to be missing entirely, so it's even hard to know whether something is clickable, and only the tooltip will tell me what it does

Screenshots:

![grafik](https://user-images.githubusercontent.com/3240233/141033445-6bf6cd15-2141-4542-8f5f-4c2253065f3a.png)
![grafik](https://user-images.githubusercontent.com/3240233/141033521-0ba9465b-6a7c-40b0-8e29-826a54af2013.png)
![grafik](https://user-images.githubusercontent.com/3240233/141033594-e5dd8a5c-5789-4951-9942-59386a563979.png)
![grafik](https://user-images.githubusercontent.com/3240233/141033643-fc86edc9-5634-40e3-ae61-8846b587030b.png)

**Comment by dragotin** [comment]
Please re-try the AppImage from https://download.opensuse.org/repositories/home:/kfreitag:/KraftAppI/AppImage/ - I just rebuild it with a few more packages in it and that solves the problem that icons were not shown at all. 

Thanks for the report!

**Comment by dragotin** [comment]
Well, the icons for Dokumente, Zeitverlauf etc. are there. The changes that solve the problem with the _same_ icons is only solved in the source tree, which is not yet in the AppImage. I do build the AppImage only from released versions, and I haven't done a release with the latest changes yet.

I have to check again about the Maßeinheiten and Identity icons tough.

**Comment by Moini** [comment]
Yep, that's what I understood from your comment above!
