### ISSUE TITLE
Please make customer address selectable in the document info at the bottom

### ISSUE THREAD

**Issue by Moini** [dragotin/kraft#122]
In the document info section at the botton, the address cannot be selected by mouse, so I need to open a document and access its header info section to be able to copy an old address (creating a copy of a document does not seem to copy the address, either).

As the AppImage does not have Akonadi access (and I don't want Akonadi on my disk, it was a waste of electricity in the background in the past and I don't need it for anything else), could the address be made more easily copiable, by making it selectable here?

![grafik](https://user-images.githubusercontent.com/3240233/141038074-8c834e23-de78-4f0c-bf46-5bb71d71dfa6.png)

**Comment by dragotin** [comment]
Interesting.. how can that be?

**Comment by Moini** [comment]
No idea, I'd assume it's an option for the GUI framework that you're using. 
E.g. I can select the stuff on the right (date, last printed), but not the address.

**Comment by Moini** [comment]
Perhaps, a little copy button would be even more useful, for AppImage users who don't have access to an addressbook. 
E.g. 'Copy address' which copies it to the clipboard on click.

**Comment by Moini** [comment]
Thank you for working on this, @dragotin !

Mmmh, now the whole section is not filled in in my build? I think that's not what was intended.

![grafik](https://user-images.githubusercontent.com/3240233/141701141-3b39a00e-29fd-4c14-b84d-1fba509d2d3c.png)

![grafik](https://user-images.githubusercontent.com/3240233/141701158-5ba7ff07-7b8a-4d87-b149-326a3f89a1a1.png)

(would you like a report about the dark theme issues?)

**Comment by Moini** [comment]
(it's not a color problem, there really is no text there, definitely not selectable)

**Comment by dragotin** [comment]
That is really strange. I tested on another computer with the latest master, and it works both on it and my usual dev machine.

I have no real idea what happens at your side. I assume you built Kraft yourself, how do you start it? With make install or without? Could you try if setting the environment variable `KRAFT_HOME` to the **source** root dir makes a difference? Kraft checks for the resources in the tree where `KRAFT_HOME` points to if it is set.

**Comment by dragotin** [comment]
Ah, well, yes.. Dark theme issues I am not sure. I am not really keen on spending effort on that, otoh dark is popular these days...

**Comment by Moini** [comment]
I built it myself, yes. Without akonadi, and with /opt/kraft prefix, in case that's important.

It works, indeed, when I set KRAFT_HOME to the git repo directory - but it can't really rely on the source directory being available, e.g. if I packaged it with checkinstall and installed the result on another computer. 

```
-- The following REQUIRED packages have been found:

 * ECM
 * Qt5Sql
 * Qt5Widgets
 * Qt5
 * Qt5Xml (required version >= 5.12.0)
 * KF5Config (required version >= 5.68.0)
 * Gettext
 * KF5I18n (required version >= 5.68.0)
 * Qt5Core (required version >= 5.12.0)
 * KF5Contacts
 * KF5
 * Qt5Gui
 * Grantlee5, Library for templating html and pdf output, <https://www.grantlee.org/>
   Optionally used for templating
 * Ctemplate
 * Qt5Test

-- The following OPTIONAL packages have not been found:

 * KF5Akonadi, Library for general Access to Akonadi, <https://www.kde.org/>
   Optionally used for addressbook integration
 * KF5AkonadiContact, Library for Accessing Contacts stored in Akonadi, <https://www.kde.org/>
   Optionally used for addressbook integration
 * Asciidoctor
```


There are a couple warnings during the build process:

`AutoMoc: /somedirname/kraft/kraft/src/kraftdoc.h:200: Warning: The property 'postText' is defined multiple times in class KraftDoc.
`

```
[ 17%] Generating ui_doctypeeditbase.h
/somedirname/kraft/kraft/src/doctypeeditbase.ui: Warning: The name 'gridLayout' (QGridLayout) is already in use, defaulting to 'gridLayout2'.
[ 17%] Generating ui_taxeditbase.h
[ 18%] Generating ui_wageseditbase.h
[ 19%] Generating ui_unitseditbase.h
[ 19%] Generating ui_importtodocbase.h
/somedirname/kraft/kraft/src/importtodocbase.ui: Warning: The name 'gridLayout' (QGridLayout) is already in use, defaulting to 'gridLayout1'.
```

```
/somedirname/kraft/kraft/src/addressprovider_akonadi.cpp: In member function ‘KContacts::Addressee AddressProviderPrivate::getAddressee(const QModelIndex&)’:
/somedirname/kraft/kraft/src/addressprovider_akonadi.cpp:204:78: warning: unused parameter ‘indx’ [-Wunused-parameter]
  204 | KContacts::Addressee AddressProviderPrivate::getAddressee(const QModelIndex& indx)
      |                                                           ~~~~~~~~~~~~~~~~~~~^~~~
/somedirname/kraft/kraft/src/addressprovider_akonadi.cpp: In member function ‘KContacts::Addressee AddressProviderPrivate::getAddressee(int, const QModelIndex&)’:
/somedirname/kraft/kraft/src/addressprovider_akonadi.cpp:220:63: warning: unused parameter ‘row’ [-Wunused-parameter]
  220 | KContacts::Addressee AddressProviderPrivate::getAddressee(int row, const QModelIndex &parent)
      |                                                           ~~~~^~~
/somedirname/kraft/kraft/src/addressprovider_akonadi.cpp:220:87: warning: unused parameter ‘parent’ [-Wunused-parameter]
  220 | KContacts::Addressee AddressProviderPrivate::getAddressee(int row, const QModelIndex &parent)
      |   
```

Afterwards, I used `make install`, and then just ran kraft from /opt/kraft/bin/kraft .

In the terminal, after starting it, it says things like:

```
Unable to find stylesheet file  "docdigestview.css"
Unable to find stylesheet file  "catalogview.css"
########## HtmlView output written to "/tmp/kraft_AhTcRf"
Unable to find stylesheet file  "systemview.css"
```

**Comment by Moini** [comment]
Selection and copying work, btw. - so the original issue here is indeed fixed!
