### ISSUE TITLE
kraft.css overwritten during update

### ISSUE THREAD

**Issue by rzlbrmft** [dragotin/kraft#126]
During every update my modified /usr/share/kraft/reports/kraft.css is overwritten with your original.
Is there any way to prevent this?

**Comment by dragotin** [comment]
Yes, just copy both the `invoice.gtmpl` and `kraft.css` into a directory in your home directory.
Go to Settings/Document Types and point the template path for the document type you want it for to that file:
![grafik](https://user-images.githubusercontent.com/1070214/145714324-84e69723-332a-4f5b-8d6d-9f6bf270033c.png)
