### ISSUE TITLE
SQLite database location

### ISSUE THREAD

**Issue by trummerschlunk** [dragotin/kraft#127]
Hi. Thanks for the software!
Is there a way to specify a location for the database (SQLite3)?
I'd like to host the database in a synchronized nextcloud folder.
Thanks!

**Comment by dragotin** [comment]
Sure, in the setup routine you can either select a "standard location" or pick the path manually.
![grafik](https://user-images.githubusercontent.com/1070214/149304009-b4a8b1a3-31d1-4a0d-bdaf-142051e92aa9.png)

**Comment by dragotin** [comment]
If you want to keep an existing sqlite db you can:
1. Shutdown kraft
2. Check in `$HOME/.config/kraftdatabaserc` where the current location is, that is key `DbFile`.
3. Copy the file from there to the new, desired location.
4. Change the path in the config above manually.
5. Start kraft and check if it is picked up correctly in the "about Kraft" page.
