### ISSUE TITLE
kde addressbook integration

### ISSUE THREAD

**Issue by trummerschlunk** [dragotin/kraft#128]
here is my next problem ;)

It seems the kaddressbook is not found or integrated. I installed kraft on arch via aur. Here is what the 'about' dialog says:

Kraft Version: | 0.97
-- | --
Codename: | Gunny
Country Setting: | United States (225)
Language Setting: | American English (31)
Database Information
Kraft database name: | 4ohm_kraft
Database schema version: | 22
Qt database driver: | QSQLITE
Database connection: | established
Addressbook Backend
Backend type: | Akonadi disabled by compile option! (not running)
External Tools
RML to PDF conversion tool: | /usr/bin/python3 /usr/share/kraft/tools/erml2pdf.py
iconv tool for text import: | /usr/bin/iconv
weasyprint for PDF generation: | not available

**Comment by dragotin** [comment]
What the About dialog says: Your version of Kraft was compiled without support for the KDE Frameworks libraries for Akonadi which are necessary to connect Kraft with the KDE Addressbook. 

Best would be to ask the Packager to fix that in his aur. He or she just needs to add the devel packages for the akonadi contacts and addressbook libs to the build environment.

**Comment by DanSman** [comment]
Hey @trummerschlunk 

I have also kraft running on Arch. I used this AUR https://aur.archlinux.org/packages/kraft/ which works fine and the maintainer is really quick fixing things if something isn't running smoothly.

Check https://wiki.archlinux.org/title/KDE#Akonadi
I have a running radicale server and no mysql setup. Might be necessary for you depending on which way you go.

Basically those were the packages `akonadi akonadiconsole kaddressbook` + `kraft` (AUR) and `akonadictl start`.

**Comment by dragotin** [comment]
I added a note on the website with the information, thanks @DanSman
