### ISSUE TITLE
Add image/logo to header

### ISSUE THREAD

**Issue by coffseducation** [dragotin/kraft#131]
Is it possible to add an image or logo of the business to the document header or elsewhere?

Thanks.

**Comment by coffseducation** [comment]
I added this code:
<image x="140mm" y="22cm" width="6cm" height="6cm" file="/home/anarcho/Pictures/art/mouseforward.png">
to the invoice.trml file but get a 'An unknown error' pop up when I 'Print document'.

**Comment by dragotin** [comment]
I added an example to the documentation: https://volle-kraft-voraus.de/Main/Documenttemplate

The error message is probably because of a typo somewhere, XML is pretty picky about that. Hint: You might have forgotten the slash before the closing bracket.

This should work:
```
<image x="140mm" y="22cm" width="6cm" height="6cm" file="/home/anarcho/Pictures/art/mouseforward.png" />
```

**Comment by coffseducation** [comment]
<image x="140mm" y="22cm" width="6cm" height="6cm" file="/home/anarcho/Pictures/art/mouseforward.png" />

Huh! Yes! Thank you!
Now displaying!
