### ISSUE TITLE
The latest version 0.98 has some issues with mysql

### ISSUE THREAD

**Issue by Dan-Sun** [dragotin/kraft#137]
Hey

I have some problems with the new version. On one computer (v. 0.98) my material lists are gone and probably other stuff too. Not the descriptions (folders), but all templates. And some templates are now in Time (changed it to Scopes). But it seems to be from an invoice, not templates from the material catalog. 
On another computer, 0.97 is still running and database schema 22, but everything is still fine there.

Any idea where to look at?

Thanks!

**Comment by Dan-Sun** [comment]
There was apparently a hiccup somehow. No idea what the problem was. But I did a mysql restore before the update. And then did everything again. This time everything works.

**Comment by dragotin** [comment]
Thanks for letting us know! :+1:
