### ISSUE TITLE
Include grantlee in the AppImage

### ISSUE THREAD

**Issue by noseshimself** [dragotin/kraft#142]
(unless you plan to remove it).

On a Debian (Googlian) I'm getting

```
Using this template:  "/home/ap/NextCloud/xxx/Kraft/reports/invoice_xxx.gtmpl"
grantlee.template: "Plugin library 'grantlee_defaulttags' not found."
Grantlee template load failed: "Plugin library 'grantlee_defaulttags' not found."
```
which might be the result of some initialization being wrong.

I used the packages provided by apt

and the libraries are on the system:

```
ap@Office:/usr/lib/x86_64-linux-gnu/grantlee/5.2$ ls -al /lib/x86_64-linux-gnu/grantlee/5.2/
insgesamt 488
drwxr-xr-x 1 root root    182 30. Jun 03:12 .
drwxr-xr-x 1 root root      6 30. Jun 03:12 ..
-rw-r--r-- 1 root root 134760 11. Jan 2021  grantlee_defaultfilters.so
-rw-r--r-- 1 root root 188256 11. Jan 2021  grantlee_defaulttags.so
-rw-r--r-- 1 root root  97248 11. Jan 2021  grantlee_i18ntags.so
-rw-r--r-- 1 root root  77224 11. Jan 2021  grantlee_loadertags.so
```

```
ap@Office:/usr/lib/x86_64-linux-gnu/grantlee/5.2$ apt search grantlee
Sortierung… Fertig
Volltextsuche… Fertig
libgrantlee-templates5/stable,now 5.2.0-3 amd64  [installiert]
  Qt-Vorlagen-Engine -- Templates

libgrantlee-textdocument5/stable,now 5.2.0-3 amd64  [installiert]
  Grantlee templating library for Qt - TextDocument

libgrantlee5-dev/stable,now 5.2.0-3 amd64  [installiert]
  Qt-Vorlagen-Engine -- Entwicklungsdateien

```

The libraries are in Debian's standard location. Please keep in mind that the system is not carrying a standard KDE/Qt5 installation which might have links to them.

**Comment by dragotin** [comment]
The original issue around grantlee should be fixed in the master builds of the AppImage available here:
https://download.opensuse.org/repositories/home:/kfreitag:/KraftAppI/AppImage/

Grantlee is looking for its plugins pretty strict in the Qt plugin dir. The grantlee package does put it somewhere else.

Fixed by a brave link in the appimage.yml that creates the AppImage in OBS by
```
  - mkdir -p $BUILD_APPDIR/usr/lib64/qt5/plugins/grantlee
  - cd $BUILD_APPDIR/usr/lib64/qt5/plugins/grantlee && ln -s ../../../grantlee/5.2 .
```

**Comment by noseshimself** [comment]
Debichrome:

All configuration files remained in place after I did

```
apt remove kraft
[download kraft-master..., copy it to /usr/local/bin and ln -s kraft-... kraft
cp kraft.desktop /usr/share/applications
kraft
```
The drama unfolds:

![image](https://user-images.githubusercontent.com/6132793/187241274-6b30f0e6-dfb8-440d-952f-70f3138da02a.png)

So it found a valid database... And wants me to create a new database:

![image](https://user-images.githubusercontent.com/6132793/187242853-8ce4f44b-9b33-4fc7-ad21-a635c9734193.png)
![image](https://user-images.githubusercontent.com/6132793/187242944-39e2e894-c92d-423e-8b88-1853ac342455.png)

What is the reason for this requiring a new setup even though there is a valid (and connectable -- I did a mysqldump before risking to destroy the data) database? I abort the setup I will get this:

![image](https://user-images.githubusercontent.com/6132793/187243925-3145c0c5-c6c8-46d8-9407-562e26684257.png)

Using another client (compiled on 20220826) shows the database still being available and working as intended.
