### ISSUE TITLE
Create an item type "comment"

### ISSUE THREAD

**Issue by dragotin** [dragotin/kraft#145]
In certain cases it could be necessary to add explanations or other additional information between items. These blocks of text should not increment item counters and anything but the text block should be invalid/ignored (especially when printing).

Please add an item type "Comment" to the list of options.

**Comment by DanSman** [comment]
Is this actually the same https://github.com/dragotin/kraft/issues/115?

**Comment by dragotin** [comment]
It is. I am closing this one in favor of #115.
