### ISSUE TITLE
Feature Request: Copying of documents should copy every non-empty field plus extending the initial default database

### ISSUE THREAD

**Issue by noseshimself** [dragotin/kraft#151]
Trying several copies of different document types (Angebot, Rechnung) not all the fields (e. g. nmanually entered address, introductory text, footer text block) were copied in all cases. Is this a bug or intended to work that way?

If so: Please

1) Offer a "full copy with all ingredients including roasted onions and mayonnaise".
2) Create a default document type "Template"/"Vorlage" for template documents including its own numbering scheme

The Template document type is intended for preparation of standard offers that are easily reusable but will not be useful if integral parts are mising in the copy.

**Comment by dragotin** [comment]
I can not reproduce this. For me, all fields are copied properly, no matter what. Are you really sure that all source documents have all texts set that you expect? Sorry for asking this question ;-)

**Comment by dragotin** [comment]
@noseshimself could you check again pls with your proper database setup? Thx.

**Comment by noseshimself** [comment]
The only thing not copied is the address field now.

**Comment by dragotin** [comment]
which is intentional. It is not likely that you will address the same doc to the same customer again.

**Comment by noseshimself** [comment]
In most cases this might be true but I'm recycling complete offers with slight changes (e. g. assessing the system security of a defined sub system where the only difference will be the time needed for single items). But as long as this is the expected behavior I can live quite well with that
