### ISSUE TITLE
Buttons in header selection screen are missing text

### ISSUE THREAD

**Issue by stefanbaur** [dragotin/kraft#154]
Hi,

The red box prompts me to click on a button with a particular label, but all four buttons are unlabeled.
This happens when using the AppImage kraft-master-0.98+git16+g89685c0-lp152.51.1.Build3.3.glibc2.17-x86_64.AppImage.

Is this a bug that only affects the AppImage, per chance, like [Issue 149](https://github.com/dragotin/kraft/issues/149#issue-1293025331)? 

-Stefan

![missing_text](https://user-images.githubusercontent.com/6331105/180234011-cec78bb9-75b3-417a-ad3a-049dbaf3c20a.jpg)

**Comment by dragotin** [comment]
Indeed same problem. I am closing this issue as duplicate. Thanks!
