### ISSUE TITLE
Bug: Can't set a document to "separate taxes per item"

### ISSUE THREAD

**Issue by noseshimself** [dragotin/kraft#158]
Whenever I try to set the Footer pull-down to "separate taxes for each item" the change is not applied.

**Comment by dragotin** [comment]
Probably also fixed by a proper database setup, right?

**Comment by noseshimself** [comment]
Probably a pilot error but I do not find any way to enter individual taxes per item. If I set an existing document to "individual taxes per item" and close it, upon opening it again it is set to the previous value.

Testing it again I can see what's going wrong. After setting the document to "individual taxes per item you actually hav to change the tax settings of at least one item to get the change to be accepted. Complicated.

[I have to debug my print templates now -- it's not printed either.]
