### ISSUE TITLE
Bug: Pull-down menus leave the visible screen

### ISSUE THREAD

**Issue by noseshimself** [dragotin/kraft#159]
(Environment: Running in a Debian container on ChromeOS with Xwayland inbetween OS environments.)

If the Kraft document window is positioned in the upper left corner of a display the document-type pop-up can partially leave the display area upwards. This obviously depends on the number of items and the currently selected item. It might be a good idea to chose another default position in that case.

**Comment by dragotin** [comment]
This sounds like window manager business. Closing, as that can not be influenced from the Kraft app.
