### ISSUE TITLE
Feature Request: Do not overwrite header/footer templates

### ISSUE THREAD

**Issue by noseshimself** [dragotin/kraft#167]
Currently adding a template will overwrite the contents of the header or footer text. This is not very useful if the templates are used as individual text blocks that are added depending on the individual needs (e. g. a remark about delivery dates, due date, travel expenses...).

The alternative is adding one, copying the field content into the paste buffer, adding another, inserting the paste buffer (repeat until all blocks are added).

**Comment by dragotin** [comment]
I think I will add another button that appends the text instead of replacing the full text. Would that work for you?

**Comment by noseshimself** [comment]
Yes, that would be a working solution.
