### ISSUE TITLE
Please bundle libxcb-keysyms.so.1 in AppImage

### ISSUE THREAD

**Issue by probonopd** [dragotin/kraft#17]
Running AppImage on Ubuntu 14.04 fails with

```
kraft: error while loading shared libraries: libxcb-keysyms.so.1: cannot open shared object file: No such file or directory
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/221

**Comment by dragotin** [comment]
You mean libxcb-keysyms.so.1 needs to be listed in the ingredients list here: https://build.opensuse.org/package/view_file/home:kfreitag:KraftAppI/kraft-appimage/appimage.yml?expand=1 ?

**Comment by probonopd** [comment]
The question is more like, why was it not installed by default. Since `kraft` seems to need it to run, it should be a dependency of the `kraft` package, and should hence be pulled in by

```
ingredients:
  packages:
    - kraft
```

Or am I overlooking something?

**Comment by dragotin** [comment]
Ah, xcb.. I guess it is pulled in via Qt. There is something fishy: On Ubuntu for example, one has to install `libxcb-xinerama0` manually. Is that a related problem? On which distro have you tried?

**Comment by probonopd** [comment]
Possibly. For the AppImage, it should be sufficient to install it on the build system and then let linuxdeployqt do its thing. In case this does still not result in it being bundled, let's discuss here further. 

Thanks.

**Comment by dragotin** [comment]
Got that as feedback on my blog:
_Trying to run the appimage on arch linux fails with: kraft: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var_

Does that mean we also need to bundle libharfbuzz?

**Comment by dragotin** [comment]
@probonopd I forgot to mention you on the previous comment...

**Comment by probonopd** [comment]
Some time ago we concluded that `libharfbuzz` should __not__ be bundled, see https://github.com/AppImage/AppImageKit/issues/454. Maybe we need to look into this again.

**Comment by probonopd** [comment]
Looks like `linuxdeployqt` didn't correctly deploy this application. For starters, `usr/bin/qt.conf` is missing which means that the Qt from the system rather than the bundled Qt is going to be used, which is a guarantee for trouble. Please remove the `|| true` from the end of the `linuxdeployqt` calls so that the build errors out when `linuxdeployqt` encounters issues.

Also, please move all Qt (dependent) packages like `libQt5Sql5-sqlite` and `qpdfview` from the `ingredients:` to the `build:` section. We don't want these to get unpacked into the AppDir directly, but we want `linuxdeployqt` to pick these up and deploy a minimal subset of them into the AppDir.

**Comment by probonopd** [comment]
Unforrtunately `libxcb-keysyms.so.1` is still missing from the AppImage.

https://github.com/dragotin/kraft/issues/17

**Comment by dragotin** [comment]
Whats the background, why do we need to add it? I will look into it.

**Comment by probonopd** [comment]
Without `libxcb-keysyms.so.1`, Kraft fails to run on Ubuntu 14.04 (the system we are testing on).

**Comment by dragotin** [comment]
I added the package to the `appimage.yml` but `libxcb-keysyms.so.1` is still not included in the resulting appimage.

The reason is probably that libxcb is in the suseexcludelist here: https://build.opensuse.org/package/view_file/OBS:AppImage/build-pkg2appimage/_service:download_url:excludesuselist?expand=1

I opened https://github.com/openSUSE/open-build-service/issues/7089 and hope for help ;-)

**Comment by probonopd** [comment]
`libxcb.so.1` should not be bundled according to 

https://github.com/AppImage/pkg2appimage/blob/e42f51314b02364497ac65286068c7f71d7779ea/excludelist#L56

But that does __not__ mean that `libxcb-keysyms.so.1` also does not need to be bundled.

**Comment by dragotin** [comment]
The AppImage is working fine now.

**Comment by probonopd** [comment]
Thank you @dragotin
