### ISSUE TITLE
Bug: Section headings in kraft(database)rc are case sensitive

### ISSUE THREAD

**Issue by noseshimself** [dragotin/kraft#173]
According to the Geneva Conventions the section headers SHOULD be case insensitive in .ini-type configuration files. ("SHOULD" meaning "there has to be a damn good reason not to do this"").

They aren't.

I had a prepared section

``[MySQL settings]``

and Kraft added

``[mysql settings]``

completely ingnoring me.

**Comment by dragotin** [comment]
While that is not nice of Kraft, that is the behaviour of the QSettings class of Qt. It is explained in the QSettings docs.
