### ISSUE TITLE
Kraft should bring its own Icons

### ISSUE THREAD

**Issue by dragotin** [dragotin/kraft#175]
There are situations where the application can not rely on an icon theme having all the required icons, as mentioned in #11 and #149:
- running on a random file manager that does not have a rich theme installed
- running on platforms that does not support packages "the linux way"
- running from AppImage.

The solution is: Kraft is brings as much icons as possible (all?) with the bundled Qt resources mechanism (compiled in).

Questions:
1. Where to pick the icons from? Best bet so far: https://github.com/tabler/tabler-icons (big set, MIT License)
2. Pick from installed theme first and fall back on the own Kraft theme or vice versa, or go with the Kraft-Theme only?

All icons we use should be available in SVG format and under a free license that is compatible with GPL.

@Moini do you want to help?

## List of Kraft Icons

First column: The name of the SVG to use - feel free to add ;-)
Second column: The name of the icon in the current source
Third column: The source files that mention the icon

### All icons picked from https://tabler-icons.io/

| new Icon Name | Icon Name in Kraft source | in files used |
| ---- | ------------------ | ------------- |
| ![plus](https://tabler-icons.io/static/tabler-icons/icons/plus.svg) plus | Add | prefsdialog.cpp, prefsunits.cpp, prefswages.cpp |
| ![arrow-down](https://tabler-icons.io/static/tabler-icons/icons/arrow-down.svg) arrow-down| Down | prefswages.cpp |
| ![pencil](https://tabler-icons.io/static/tabler-icons/icons/pencil.svg) pencil| Edit | prefsunits.cpp, prefswages.cpp |
| ![X](https://tabler-icons.io/static/tabler-icons/icons/x.svg) X| Remove | prefsdialog.cpp, prefsunits.cpp, prefswages.cpp |
| ![receipt-tax](https://tabler-icons.io/static/tabler-icons/icons/receipt-tax.svg) receipt-tax| Taxes | prefsdialog.cpp |
| ![atom](https://tabler-icons.io/static/tabler-icons/icons/atom.svg) atom| Units | prefsdialog.cpp |
| ![arrow-up](https://tabler-icons.io/static/tabler-icons/icons/arrow-up.svg) arrow-up| Up | prefswages.cpp |
| ![cash-banknote](https://tabler-icons.io/static/tabler-icons/icons/cash-banknote.svg) cash-banknote | Wages | prefsdialog.cpp |
| ![calculator](https://tabler-icons.io/static/tabler-icons/icons/calculator.svg) calculator | accessories-calculator | templkataloglistview.cpp |
| ![logout](https://tabler-icons.io/static/tabler-icons/icons/logout.svg) logout | application-exit | portal.cpp |
| ![arrow-down](https://tabler-icons.io/static/tabler-icons/icons/arrow-down.svg) arrow-down| arrow-down | positionviewwidget.cpp |
| ![arrow-up](https://tabler-icons.io/static/tabler-icons/icons/arrow-up.svg) arrow-up| arrow-up | positionviewwidget.cpp |
| ![check](https://tabler-icons.io/static/tabler-icons/icons/check.svg) check | checkmark | prefsdialog.cpp |
| ![arrows-up-down](https://tabler-icons.io/static/tabler-icons/icons/arrows-up-down.svg) arrows-up-down| configure | positionviewwidget.cpp |
| ![file-x](https://tabler-icons.io/static/tabler-icons/icons/file-x.svg) file-x| document-delete | katalogview.cpp |
| ![edit](https://tabler-icons.io/static/tabler-icons/icons/edit.svg) edit| document-edit | doctypeedit.cpp, flostempldialog.cpp, katalogview.cpp, portal.cpp |
| ![file-export](https://tabler-icons.io/static/tabler-icons/icons/file-export.svg) file-export| document-export | portal.cpp |
| ![file-plus](https://tabler-icons.io/static/tabler-icons/icons/file-plus.svg) file-plus| document-new | docassistant.cpp, katalogview.cpp, portal.cpp |
| ![template](https://tabler-icons.io/static/tabler-icons/icons/template.svg) template| document-new-from-template | portal.cpp |
| ![eye](https://tabler-icons.io/static/tabler-icons/icons/eye.svg) eye| document-preview | portal.cpp |
| ![printer](https://tabler-icons.io/static/tabler-icons/icons/printer.svg) printer| document-print | portal.cpp |
| ![edit](https://tabler-icons.io/static/tabler-icons/icons/edit.svg) edit| document-properties | docassistant.cpp |
| ![copy](https://tabler-icons.io/static/tabler-icons/icons/copy.svg) copy | edit-copy | portal.cpp, prefsdialog.cpp |
| ![cut](https://tabler-icons.io/static/tabler-icons/icons/cut.svg) cut| edit-cut | portal.cpp |
| ![minus](https://tabler-icons.io/static/tabler-icons/icons/minus.svg)| edit-delete | docassistant.cpp, positionviewwidget.cpp |
| ![transfer-in](https://tabler-icons.io/static/tabler-icons/icons/transfer-in.svg)transfer-in| edit-paste | portal.cpp |
| use lock| encrypted | positionviewwidget.cpp |
| ![archive](https://tabler-icons.io/static/tabler-icons/icons/archive.svg) archive| file-library-symbolic | portal.cpp |
| ![file-plus](https://tabler-icons.io/static/tabler-icons/icons/file-plus.svg) file-plus| filenew | positionviewwidget.cpp |
| ![flag](https://tabler-icons.io/static/tabler-icons/icons/flag.svg) flag| flag | positionviewwidget.cpp |
| ![edit](https://tabler-icons.io/static/tabler-icons/icons/edit.svg) edit| folder-documents | katalogview.cpp, prefsdialog.cpp |
| ![arrow-narrow-left](https://tabler-icons.io/static/tabler-icons/icons/arrow-narrow-left.svg) arrow-narrow-left| go-previous | docassistant.cpp, textselection.cpp |
| ![help](https://tabler-icons.io/static/tabler-icons/icons/help.svg) help | help-about | portal.cpp |
| ![arrow-ramp-right](https://tabler-icons.io/static/tabler-icons/icons/arrow-ramp-right.svg) arrow-ramp-right| kraft_alternative | positionviewwidget.cpp |
| ![arrow-move-right](https://tabler-icons.io/static/tabler-icons/icons/arrow-move-right.svg) arrow-move-right| kraft_demand | positionviewwidget.cpp |
| ![coin](https://tabler-icons.io/static/tabler-icons/icons/coin.svg) coin| kraft_fulltax | kraftview.cpp, positionviewwidget.cpp |
| ![circle-0](https://tabler-icons.io/static/tabler-icons/icons/circle-0.svg) circle-0| kraft_notax | kraftview.cpp, positionviewwidget.cpp |
| ![circle-half-2](https://tabler-icons.io/static/tabler-icons/icons/circle-half-2.svg) circle-half-2| kraft_redtax | kraftview.cpp, positionviewwidget.cpp |
| ![dice](https://tabler-icons.io/static/tabler-icons/icons/dice.svg) dice | kraftdice | templkataloglistview.cpp |
| plus (see add)| list-add | doctypeedit.cpp, flostempldialog.cpp, numbercycledialog.cpp |
| minus (see remove)| list-remove | doctypeedit.cpp, flostempldialog.cpp, numbercycledialog.cpp |
| ![mail-forward](https://tabler-icons.io/static/tabler-icons/icons/mail-forward.svg) mail-forward| mail-forward | portal.cpp |
| ![lock](https://tabler-icons.io/static/tabler-icons/icons/lock.svg) locked| object-locked | positionviewwidget.cpp |
| ![lock-open](https://tabler-icons.io/static/tabler-icons/icons/lock-open.svg) lock-open| object-unlocked | positionviewwidget.cpp |
| ![language](https://tabler-icons.io/static/tabler-icons/icons/language.svg) language| preferences-desktop-locale | kraftdocheaderedit.cpp |
| ![device-floppy](https://tabler-icons.io/static/tabler-icons/icons/device-floppy.svg) device-floppy| quickopen-file | doctypeedit.cpp, prefsdialog.cpp |
| ![minus](https://tabler-icons.io/static/tabler-icons/icons/minus.svg) minus| remove | positionviewwidget.cpp |
|![settings](https://tabler-icons.io/static/tabler-icons/icons/settings.svg) settings| settings-configure | portal.cpp |
|![user-identiy](https://tabler-icons.io/static/tabler-icons/icons/id-badge-2.svg) id-badge-2 | user-identity | prefsdialog.cpp |

**Comment by noseshimself** [comment]
Mail Forward: https://tabler-icons.io/i/mail-forward is not looking too bad either.

User-Identity: https://tabler-icons.io/i/id-badge-2

Settings? The usual suspects: https://tabler-icons.io/i/settings https://tabler-icons.io/i/tool

Locked/unlocked? https://tabler-icons.io/i/lock-open https://tabler-icons.io/i/lock

Help: https://tabler-icons.io/i/help

https://tabler-icons.io/i/plus
https://tabler-icons.io/i/minus
