### ISSUE TITLE
Feature Request: MySQL reconnect after loss of connection.

### ISSUE THREAD

**Issue by noseshimself** [dragotin/kraft#183]
I noticed that Kraft is not reconnecting after losing its database connection nor is it gracefully shutting down.The only thing hinting at this problem are console messages (which are only visible if Kraft is launched from a terminal) and the fact that it is hanging "somehow".
Reconnecting might be the better choice...

**Comment by dragotin** [comment]
Reference: https://dev.mysql.com/doc/c-api/8.0/en/c-api-auto-reconnect.html
