### ISSUE TITLE
How to test translation?

### ISSUE THREAD

**Issue by narcisgarcia** [dragotin/kraft#190]
I'm contributing to a localization translation.
I'm using Kraft 0.96 from Debian (stable) repositories.

How can I download~apply these translation "as is" to my Kraft instance?

**Comment by dragotin** [comment]
Interesting question - which I can not completely answer. 

What should work: Your packages should load the translations from a file such as `/usr/share/locale/de/LC_MESSAGES/kraft.mo` - depending on your language with another locale name. 

If you put your work kraft.mo there, ie. to `/usr/share/locale/es/LC_MESSAGES/kraft.mo` that should work.

To get the mo-file out of the po file you can use the tool `msgfmt` from gettext.

There might be better ways to do that that I do not know.

Note: Version 0.96 is already a bit old - so not _all_ strings might be used. Keep that in mind.

**Comment by dragotin** [comment]
@narcisgarcia any luck? Are you working on translations?
