### ISSUE TITLE
Signature text missing and footer needs more data

### ISSUE THREAD

**Issue by Zorandon** [dragotin/kraft#200]
First, this is very helpful and nice software.
Now, I cannot figure out how to place my printed name underneath the greeting "best regards". Also the footer is lacking data like the IBAN and tax number. In my personal information I left out Fax, but "FAX:" ist still shown in the footer. Do I miss something, or are the features just not there, yet. Thanks.

**Comment by dragotin** [comment]
I assume this refers to the generated PDF, right?

If you want to change that, you need to tweak the template that is used to generate the the PDF.
See here for a pointer to start: https://dragotin.github.io/krafthandbook/manuals/kraft-en.html#_output_document_customization

Let me know if you can solve your problem with that.

**Comment by Zorandon** [comment]
Yes, I mean the generated PDF as the end result, but I  was looking for a way to e.g. insert my printed name unterneath the "Mit freundlichen Grüßen" through the GUI. I figured out how to edit the template for the pdf, now. I someow overlooked that it has to be done this way. Generally it would be great to be able to insert bank account, tax number etc. via the GUI. But that solves the issue, thank you.
