### ISSUE TITLE
Defective icon in AppImage

### ISSUE THREAD

**Issue by probonopd** [dragotin/kraft#206]
Thanks for making an AppImage.

Found a small and easy to fix issue with `Kraft-v1.0-x86_64.AppImage`: 
The `.DirIcon` in the AppImage links to a file with `.svg` suffix that actually contains HTML.

As a result, file managers can't show the Kraft icon.

**Comment by dragotin** [comment]
This is already fixed in 535a5a5e1545afd7b250bf8120be7c352b1225fb - but that fix came in after 1.0 and is still to release.

This continous AppImage build should be ok: https://github.com/dragotin/kraft/suites/14906826337/artifacts/849435417

Thanks for reporting!
