### ISSUE TITLE
Building from tarball fails

### ISSUE THREAD

**Issue by EbonJaeger** [dragotin/kraft#211]
This commit (https://github.com/dragotin/kraft/commit/e9aa6e953243848a5f8acf5958d7c6fd5e68339d) tries to check for a `.tag` file in the absence of a `.git` directory, but there is no such file in the GitHub auto-generated source tarballs. I think for this to work, you would have to tar the source directory yourself and upload it when making the release. Projects that do this generally script it to minimize the effort.

**Comment by dragotin** [comment]
Ok, thanks for the report, this is annoying.

The quick fix is to create a file `.tag` in the root of the unpacked tarball which should contain the SHA of the last commit.

This command creates a correct tarball: 
`git archive --format=tar --prefix=kraft-1.1/ --add-file=.tag v1.1 | xz>kraft-1.1.tar.xz`

It would be awesome if Githubs release mechanism would include that as an option.
