### ISSUE TITLE
Transparent image-background is transformed into black, when printing (invoice.trml)

### ISSUE THREAD

**Issue by bastelinsky** [dragotin/kraft#218]
Once again me. Meanwhile I found the row in the .trml-file for the Logo and changed it to my needs.
Unfortunately every transparent background in  .png's are printed in black. I tried several programs to save the png again, but without success.
Any help?
I guess I can't be the only one with this issue.

Thanks for your support.
Wolfgang

**Comment by dragotin** [comment]
Note to self: https://stackoverflow.com/questions/45092929/reportlab-python-transparent-background-is-changed-to-black-and-poor-image-qual

**Comment by dragotin** [comment]
Fixed with the referenced commit, thank you for reporting.
