### ISSUE TITLE
Add the option for selecting a font to kraftrc

### ISSUE THREAD

**Issue by noseshimself** [dragotin/kraft#219]
I guess I have to return to https://github.com/dragotin/kraft/issues/148 once more.

After getting a new ChromeBook and a Huawei MateView with an incredible resolution but... I don't have much control over the settings of individual applications (or the theming delivered by their environment); they do have to do things.

Please add an option to select a font family and base size to the kraftrc in case a device dependent setting is required.

**Comment by dragotin** [comment]
Oh no, that I do not want to do. The font settings for apps are under the control of the desktop environment.

Please check the env var `QT_SCALE_FACTOR` and https://askubuntu.com/questions/1095803/creating-desktop-launcher-with-qt-scale-factor on how to fix your issue.
