### ISSUE TITLE
Units should be translatable

### ISSUE THREAD

**Issue by bitigchi** [dragotin/kraft#229]
Units are not generally locale-dependent, they can just be translated, since they are universal after all.

![Ekran Görüntüsü_20240321_170122](https://github.com/dragotin/kraft/assets/2769571/37bfd3ef-da0b-4874-8097-7bfe46a0b49c)

Latest master.

**Comment by dragotin** [comment]
Well, they can be added by the user, in the requested language. That is part of the setup routine.

I am not planning to build a translation mechanism for them currently.
