### ISSUE TITLE
Add Turkish translation

### ISSUE THREAD

**Issue by bitigchi** [dragotin/kraft#230]
I plan to work on this, but I will wait for the moment for a .pot file update (especially for #226, #229, and #231).

**Comment by dragotin** [comment]
The PRs are merged, and I updated the pot file in Transifex and added Turkish as a language.

Please see https://app.transifex.com/kraftproject/kraft/dashboard/

**Comment by dragotin** [comment]
Feel free to re-open in case you work on it and need some help.
