### ISSUE TITLE
xrechnungs export inactivated

### ISSUE THREAD

**Issue by arendvogtlaender** [dragotin/kraft#235]
Hi, 

on my kraft installation, the xrechnung export menuitem is not usable.
I followed the instructions adapting the xrechnung template and chose it in the settings dialog. 
but after that the menuitem for xrechnung export is not active.
what have I missed?

this is a brandnew opensuse leap 15.5, running inside a hyper-v cluster. 
kraft was installed via yast

thanks for any hints, 
arend

**Comment by dragotin** [comment]
The menu item is only enabled if the document type is called "Rechnung". That is a cheap work around to identify doctypes which are actually invoices. Bad idea... I know. Now that I know that people are starting to use that feature, I can come up with a better solution like a checkbox in the Settings dialog "This is an invoice"

Maybe you want to test with a document type called "Rechnung" for now.

**Comment by arendvogtlaender** [comment]
Hi,

yes, I suspected that the document type was relevant, but it seems not to work with „Rechnung“ either.
I tried to enter „XRechnung 2.0“ As an DocumentType, but that would’t change anything. Was worth a shot though 😊

Here’s a screenshot oft he contextmenu:
***@***.***

I also validated the xrechnung.xrtmpl, it is ok.

Are there any properties for the app, that can be fiddled with?
Is it possible to activate some sort of logging?


Viele Grüße,
Arend Vogtländer
Solution Engineer
--
Governikus GmbH & Co. KG
Hochschulring 4
28359 Bremen, Germany

Telefon: +49 421 204 95 - 933
Mobil: +49 151 74215702
Fax: +49 421 204 95 - 11
E-Mail: ***@***.******@***.***>
www.governikus.de<http://www.governikus.de/>

Von: Klaas Freitag ***@***.***>
Gesendet: Mittwoch, 1. Mai 2024 10:18
An: dragotin/kraft ***@***.***>
Cc: Vogtländer, Arend ***@***.***>; Author ***@***.***>
Betreff: Re: [dragotin/kraft] xrechnungs export inactivated (Issue #235)

ACHTUNG: Diese E-Mail stammt von einem externen Absender. Bitte vermeide es, Anhänge oder externe Links zu öffnen.


The menu item is only enabled if the document type is called "Rechnung". That is a cheap work around to identify doctypes which are actually invoices. Bad idea... I know. Now that I know that people are starting to use that feature, I can come up with a better solution like a checkbox in the Settings dialog "This is an invoice"

Maybe you want to test with a document type called "Rechnung" for now.

**Comment by dragotin** [comment]
Well, please try wih the default document type "Rechnung". It is a dumb string compare checking strictly for the term `Rechnung` that. Not cool. I will change that. 

Logging: kraft uses `qDebug()`, starting it in a terminal will spit out logging.

**Comment by arendvogtlaender** [comment]
it seems to be the problem that in my installation the proposed solution does not work.

![kraft_no-export-available](https://github.com/dragotin/kraft/assets/52319596/142800d3-a6e5-42a4-bb4c-e1c540851731)
whatever I do, the menuitem stays gray.

i tested a bit around if maybe something in the Kontact-data used for addressing was missing, but without success.
is it possible to raise the verbosity for logging? 
i just found stuff to raise it programatically, but not on the command line.

**Comment by dragotin** [comment]
Hm, have you specified the template to use in the Kraft settings dialog?
![settings_doctype](https://github.com/dragotin/kraft/assets/1070214/15a69cff-e88c-4443-977b-d16c557b7d84)
