### ISSUE TITLE
is generic export of documents possible?

### ISSUE THREAD

**Issue by bobster-galore** [dragotin/kraft#26]
As well it would be nice to make a generic export of documents possible.
Any ideas?

**Comment by dragotin** [comment]
There are already tow types of exports: 
Per default documents are saved under `$HOME/.local/share/kraft`, both as PDF file and as XML encoded file.

Also, in the same directory, documents are saved in a tree built from the customer address ID, followed by the document type. That way, it is is possible to quickly look up the documents that were sent to a customer for third party tools. 
See also the tool `findcontact` related to this.

What else would you propose?

**Comment by bobster-galore** [comment]
I can not propose smthg right now. I only thought about smthg nicer than copy&paste from pdf-documents. So it could be some kind of parsing xml.
I will see when I cross the bridge.

**Comment by dragotin** [comment]
Any more input on this?

**Comment by dragotin** [comment]
closing.
