### ISSUE TITLE
make document type configurable

### ISSUE THREAD

**Issue by bobster-galore** [dragotin/kraft#27]
It would be desirable to add custom text to drop down to
* add translations
* just another wording
* custom text

which could be achieved by 
* just entering in drop down
* add in expert settings
* fumble in the database

**Comment by dragotin** [comment]
Have you seen the configuration dialog in Settings/Configure Kraft ?

![screenshot_20180210_105226](https://user-images.githubusercontent.com/1070214/36060792-9010feea-0e50-11e8-8d7d-3f2d8544956b.png)

There you can add new doc types and edit the most important things around them.

**Comment by bobster-galore** [comment]
Oic, very nice! That's what I was asking for.
