### ISSUE TITLE
new address not working

### ISSUE THREAD

**Issue by bobster-galore** [dragotin/kraft#29]
In recent beta it is not possible to enter a new address.
"Adressaten auswählen"
"Here u can enter a new address"
Which doesn't open anything and it's as well not possible to enter a new address manually.
May be "entering an address manually" could be a feature?!

**Comment by dragotin** [comment]
Are you using the AppImage or a Package? 

Which address (own address or customer address?) do you mean? Where do you see the "Adressaten auswählen" text? Please try to explain more exact, maybe with screenshot.

Works here with my self compiled Kraft in the document edit window for Header.

**Comment by bobster-galore** [comment]
As suggested I installed openSUSE Leap 42.3 and https://software.opensuse.org/ymp/home:kfreitag:Kraft/openSUSE_Leap_42.3/kraft.ymp?base=openSUSE%3ALeap%3A42.3&query=kraft
Later I started kraft / new document / document details / "Adressaten auswählen":
"If there is no contact already, you can open your addressbook here and add a new contact."
But I can't  open anything.

**Comment by dragotin** [comment]
Perfect, thanks for the report. Fixed with commit 19a5593b34bd4d790b9c4e8a346c2898a61a4008
