### ISSUE TITLE
Bug - Margin option (Template)

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#42]
Hi

If I wanna add some Margin in a Template it's showing at the bottom of the template that I added 10% Margin (Overall Price per Unit) but when I close my catalog, the "hint" will be gone, but the price will remain unchanged and I don't know how the price actually came to that conclusion if I have to change the price again in the future. 

Thanks,
Dan

**Comment by dragotin** [comment]
Cleaned up the dialog while fixing this:

![templdialog](https://user-images.githubusercontent.com/1070214/46728916-37e05c00-cc84-11e8-9af9-8392b2ad6017.png)
