### ISSUE TITLE
Bug - TimeCalculation behind komma

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#43]
Hi

(Painting Business)

It would be great to have the possiblity to write the time behind komma/dot. Not only full minutes.

Example: 
I need 2.49 minutes per sqm to paint a ceiling but I can only chose 2 or 3 minutes. If I had a 1037 sqm ceiling/s, I would need only 2582.13minuts with 2.49min/sqm.
3 minutes = 3111minutes
2 minutes = 2074 minutes
The difference is just too big for me or the customer.

Thanks,
Dan

**Comment by dragotin** [comment]
Would it be a good solution if you could choose in the time if you calculate minutes or seconds (or maybe other units like industry-minutes) within the time calc dialog?

Like this:
![newtimecalc](https://user-images.githubusercontent.com/1070214/44658414-088dcc80-aa01-11e8-9b63-07d239ac0ea1.png)

**Comment by DanSman** [comment]
Hey

I just realized that I can not use more than 2 digits.

I have a time which is 1022 seconds or 17 min and 2 sec. I don't care about the 2 sec. But if it's 30 seconds that'll be a big difference again.
