### ISSUE TITLE
Price for materials in documents

### ISSUE THREAD

**Issue by SmokeMaster1** [dragotin/kraft#48]
I add "Material A" with a price of 10€ per unit and 10 units per package -Material A has a (correct) total price of 10€.
I add Material A to a "Standard Text" with 1 Unit and Kraft display this correct with a price of 1€.
But if i directly add Material A to a document, 1 Unit is displayed with a price of 10€.

**Comment by dragotin** [comment]
Fixed by the mentioned commit, thanks for reporting.
