### ISSUE TITLE
Create new translations

### ISSUE THREAD

**Issue by aseques** [dragotin/kraft#49]
Kraft 0.80 is now on ubuntu (18.10), I wanted to start a translation into my language (catalan), could you upload it to somewhere like weblate.org so I can start the translation?
I saw that there are some issues alterady fixed on 0.82, but at the moment I'll keep using the program in english until updated on ubuntu

**Comment by dragotin** [comment]
A project on Transifex was created: https://www.transifex.com/not-applicable-6/kraft/settings/

Please join there. 

If other languages are needed, please let me know here.

Thanks for this report.

**Comment by aseques** [comment]
The link is wrong, it should point to https://www.transifex.com/not-applicable-6/kraft/

**Comment by dragotin** [comment]
Cool, thanks!

**Comment by dragotin** [comment]
Sorry, I only realized today that I have to accept the request to become a translator for Kraft. Did that now, and switched to "auto-accept".

**Comment by aseques** [comment]
Working now 👍
