### ISSUE TITLE
Manage contacts without akonadi

### ISSUE THREAD

**Issue by aseques** [dragotin/kraft#50]
I am trying to setup kraft, and one of the things I wanted to do was to import the contacts I have exported to a csv.
Is there any way to import those contacts at the moment when using a system without akonadi?

Thanks

**Comment by dragotin** [comment]
No. Kraft does not have its own address management, it relies on Akonadi here. If there is no Akonadi, the customer addresses are only stored with the document, which is very simple. However, enhancing that would mean re-implementing Akonadi which is not in my focus.

Please try to setup and use kaddressbook with Akonadi, you wont regret :)

Thanks for your report!

**Comment by aseques** [comment]
Ok, I'll check it out, I haven't tried akonadi since a lot of time, and I'll see how it goes.

**Comment by dragotin** [comment]
Cool. My feeling is that akonadi and friends have matured a lot, definetely worth a try. The address management with kaddressbook is on a superb level, it would not make any sense to have something comparable in Kraft.

**Comment by aseques** [comment]
I just tried it, it definitely has improved a lot since last time I tried, there are still some rough edges (see [here](https://bugs.kde.org/show_bug.cgi?id=385510) or [here](https://forum.kde.org/viewtopic.php?f=215&t=153366&p=406478#p401738)) but overall is quiet usable
