### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#56]
Hello.

I had to install Kraft again because I wanted to start from scratch.

As you maybe know I'm using Arch as a System and it's might be related to Arch and my setup of Arch. But I thought I ask you at first.

```
catalogchapter.cpp:20:
/usr/include/qt/QtSql/qsqlrelationaldelegate.h:115:52: error: ‘QByteArray::operator QNoImplicitBoolCast() const’ is private within this context
                     v = QVariant(editor->property(n).userType(), nullptr);
```

```
catalogchapter.cpp:20:
/usr/include/qt/QtSql/qsqlrelationaldelegate.h:116:37: error: invalid user-defined conversion from ‘QByteArray’ to ‘const char*’ [-fpermissive]
                 editor->setProperty(n, v);
```

```
catalogchapter.cpp:20:
/usr/include/qt/QtSql/qsqlrelationaldelegate.h:116:41: error: ‘QByteArray::operator QNoImplicitBoolCast() const’ is private within this context
                 editor->setProperty(n, v);
```

I searched for this issue a little but I couldn't find the right answer. Do you have any idea to solve this issue?

Regards,
Dan

**Comment by t-8ch** [comment]
It works on the master branch. I will backport the fixes to the arch package.

**Comment by t-8ch** [comment]
Applying 3ac6fb9 fixed the broken build.

**Comment by DanSman** [comment]
Thank you very much.

It's working again!
