### ISSUE TITLE
Bug with changed Material price

### ISSUE THREAD

**Issue by SmokeMaster1** [dragotin/kraft#57]
After changing the price of a material in the "Material Catalogue", the material is deleted from calculated "Standart Text Catalogue" Entrys.

**Comment by SmokeMaster1** [comment]
Would be better to change the price in every entry or display an "alert" for the changes

**Comment by dragotin** [comment]
It looks like the template looses one calculation part, I could reproduce a case with a material and a time component, and the latter was lost.

**Comment by dragotin** [comment]
More testing makes me confident that this is fixed. Thanks for the report!
