### ISSUE TITLE
Splash screen shows old version

### ISSUE THREAD

**Issue by t-8ch** [dragotin/kraft#68]
The splashscreen in 0.90 still shows the previous version.

![splash screen](https://github.com/dragotin/kraft/raw/v0.90/src/pics/kraftsplash.png)

**Comment by dragotin** [comment]
Yes, unfortunately.... 

But not _that_ critical I guess ;-)

**Comment by t-8ch** [comment]
Absolutely not 😃

**Comment by dragotin** [comment]
Well, aside from joking... A well prepared release checklist would prevent this kind of mistakes. 

Here we go: ce2d78452512cee2ac1081b3637e298296531926

Feel free to add things to remember...

**Comment by t-8ch** [comment]
Is the version in the splash screen really useful at all?
The version can be retrieved from the   package manager or "About" screen.

**Comment by dragotin** [comment]
Yes, good point. Or even more, is the splash-screen useful at all? The startup time of Kraft should be fairly short, so maybe we should just drop it and come up with the main window right away?

**Comment by t-8ch** [comment]
If Kraft supports proper startup notifications and therefore the desktop environment can provide startup feedback then it probably isn't really helpful.

**Comment by dragotin** [comment]
removed the splash screen in commit 50452ffc056c0e90bdbbf827ec46bad71e4e539f
