### ISSUE TITLE
Kraft posts error on Printing 

### ISSUE THREAD

**Issue by Xastrax** [dragotin/kraft#73]
Good Evening,
i am new to craft, i have a very big problem. 
every time i try to print to PDF i get this error
`Traceback (most recent call last):
  File "/usr/share/kraft/tools/erml2pdf.py", line 931, in <module>
    pdf = parseString( open( infile, 'r' ).read() )
  File "/usr/share/kraft/tools/erml2pdf.py", line 876, in parseString
    r = _rml_doc(data.strip())
  File "/usr/share/kraft/tools/erml2pdf.py", line 307, in __init__
    self.dom = xml.dom.minidom.parseString(data)
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 191, column 64
`
my system specc is
`
OS: openSUSE Leap 15.1 x86_64 
Host: 2537AT1 ThinkPad T410 
Kernel: 4.12.14-lp151.28.36-default 
Uptime: 1 hour, 12 mins 
Packages: 2309 (rpm), 6 (snap) 
Shell: bash 4.4.23 
Resolution: 1440x900 
DE: KDE 
WM: KWin 
WM Theme: RevengeShip 
Theme: RevengeShip [KDE], Adwaita [GTK2], Breeze [GTK3] 
Icons: RevengeShip [KDE], Adwaita [GTK2], RevengeShip [GT 
Terminal: konsole 
CPU: Intel i5 M 560 (4) @ 2.667GHz 
GPU: Intel Core Processor 
Memory: 2303MiB / 3736MiB 
`

**Comment by dragotin** [comment]
Have you  changed the document template? If so, could you attach an example doc here?

**Comment by Xastrax** [comment]
no nothing. for testing the program i entered my Company details an started entereing a few example entrys

**Comment by dragotin** [comment]
Can you try to pass me the document that is failing, either by attaching here or per PM to kraft@freisturz.de ?

If the generation fails you should find the generated file in `/tmp`, it is called `kraft.<id>` where id is a six char id. That file (it is a XML'ish file) I would need to check. Thanks!

**Comment by Xastrax** [comment]
[tmp_1.zip](https://github.com/dragotin/kraft/files/4172888/tmp_1.zip)
 i packed all kraft files i could find into an archive

**Comment by dragotin** [comment]
That is really strange because all of these files are not complete. They end within the header text.
```
       <para style="text">Wir haben gemäß dem uns erteilten Auftrag nachfolgend aufgeführte Lieferungen und Leistungen erbracht und berechnen Ihnen
```
are the last two lines.

There is something special in the header, but  I can not see what. Do you have an idea?

**Comment by dragotin** [comment]
Hm, no, there are also files that end later, within the items. I am really lacking ideas how that could have happened.

**Comment by Xastrax** [comment]
i tested it a few days but i couldnt find the right thing that triggers the error. 

first the error was only on uneven numbers
then as i created entrys with even numbers it started trowing errors after i entered the material. 
the last test was that i entered the customers name and added only one item ant the error popped up.

**Comment by dragotin** [comment]
I finally found the reason for the cut template file: The input stream contains a zero. And as a result, the `c_str()` in [this line](https://github.com/dragotin/kraft/blob/master/src/texttemplate.cpp#L177) stops at the zero. 

The interesting question is, however, where does the zero come from? It is not at the same places.

**Comment by dragotin** [comment]
In this case, the zero is stored in the database:

```
MariaDB [kraft_kfg]> select hex( LEFT(salut, 5)), LEFT(salut,5) from document where ident = '201510-2026';
+----------------------+---------------+
| hex( LEFT(salut, 5)) | LEFT(salut,5) |
+----------------------+---------------+
| 0053656872           |  Sehr         |
+----------------------+---------------+
```
(note the leading 00) - which is not displayed in the second column.

**Comment by dragotin** [comment]
I pushed a fix that removes zero chars from the output stream to master: 8ebadc5cee81e9c1f95a08b1bc937108b1421494

@Xastrax would you be able to test if that fixes your problem?

**Comment by dragotin** [comment]
Assuming that this is fixed with the commit above.
