### ISSUE TITLE
Start issue

### ISSUE THREAD

**Issue by rzlbrmft** [dragotin/kraft#81]
I updated from openSUSE 15.1 to 15.2 on 2 devices.
On the one kraft does work fully as before, on the other one I receive following when starting kraft in terminal and kraft crashes:

Found this stylefile:  "/usr/share/kraft/styles/docdigestview.css"
Found this stylefile:  "/usr/share/kraft/styles/catalogview.css"
Found this stylefile:  "/usr/share/kraft/styles/systemview.css"
kraft: symbol lookup error: kraft: undefined symbol: _ZN9KContacts13AddresseeListC1Ev

**Comment by rzlbrmft** [comment]
Solution:
I carried out an update of kraft and then following has been installed additionally and now it works. Seems these have been removed during the update from openSUSE 15.1 to 15.2 on the 1 device automatically.
python-xml
python2-PyPDF2
python2-olefile
python2-six
python2-Pillow
python2-reportlab

**Comment by dragotin** [comment]
This looks like you have Kraft from a different repository. Are you sure that it was updated from the right repo?

**Comment by rzlbrmft** [comment]
I did have kraft from the openSUSE main repository - now I use it from https://download.opensuse.org/repositories/KDE:/Extra/openSUSE_Leap_15.2/ and it works.
