### ISSUE TITLE
The post-it image background is not transparent

### ISSUE THREAD

**Issue by krop** [dragotin/kraft#83]
Using kraft 0.95 from openSUSE. The post-it icon on the main window has a white background which doesn't look very nice when using dark color schemes.

![Screenshot_20200901_122105](https://user-images.githubusercontent.com/1181826/91838439-089eb380-ec3d-11ea-98c4-3617d93ca04b.png)

**Comment by dragotin** [comment]
The new image makes it appear like this: 
![ksnip_20200902-180436](https://user-images.githubusercontent.com/1070214/92010329-f8c0c580-ed49-11ea-8fb8-0f9d34369dc1.png)
![ksnip_20200902-180634](https://user-images.githubusercontent.com/1070214/92010330-f9595c00-ed49-11ea-841b-da6a02018bbe.png)
I actually like the blurred appearance in the dark theme.
