### ISSUE TITLE
credit note (Gutschrift) does not show VAT

### ISSUE THREAD

**Issue by rzlbrmft** [dragotin/kraft#88]
On kraft 0.95 (as on 0.90) I try to write a credit note (Gutschrift) with negative value.
The net value (Netto) is correct, the gross value (Brutto) as well as it includes the VAT which is negative, but the line where I would expect the (negative) VAT is empty.
-100 EUR net 
-16 EUR tax [not shown]
-116 EUR gross

**Comment by rzlbrmft** [comment]
It works fine with WeasyPrint

**Comment by dragotin** [comment]
Are you saying that it is just not shown on the PDF document generated with the reportlab based (old) system, but it is ok with the weasyprint generator?

**Comment by rzlbrmft** [comment]
Yes, the negative VAT is not shown on the PDF document generated with the reportlab 
based (old) system, but it is ok with the weasyprint generator!
-----Original Message-----
