### ISSUE TITLE
Timeline overview calculation is wrong after hard remove of document

### ISSUE THREAD

**Issue by oyla12** [dragotin/kraft#89]
Moin

**At first: I'm sure this is not a usual case and may not need a fix. So just as informal transparency:**

As I started using the software I added the first document (bill) for testing purposes. By testing I realised, I'm willing to change the invoice number system  and tried to delete the (testing) document. This was not really possible over the interface (as I may see as feature for clean invoice management), so I removed it from database by sqllitebrowser.

As I now made my sales tax summary report (GER: "Umsatzsteuervoranmeldung") I was very happy about the Timeline feature. But than I realized, that he is summing up over 4 documents (and not as it should be 3). There seems to be the old document involved and as result the calculation is not correct. 

**Timeline Overview**
![Screenshot_2020-11-15_23-13-35](https://user-images.githubusercontent.com/24416548/99199631-c814f780-27a0-11eb-8def-5099c0f6d3da.png)

**Documents of this Month**
![Screenshot_2020-11-15_23-14-04](https://user-images.githubusercontent.com/24416548/99199632-c814f780-27a0-11eb-99cf-378230d60830.png)

I was manually looking into the database and not sure, were he gets the information about the document I deleted. As database corruption may be always a problem I would expect that the shown calculation is exactly based on what I can the in the documents overview.

Whatever: Thanks for your work, I'm very happy about using your software, it's the simple solution I've looked for :)

ahoi!
oyla

**Comment by dragotin** [comment]
The list is generated from the table `archdoc` which contains the archived documents, ie. the ones that have been printed. From that, it takes the latest one printed.

Kraft is still lacking a flag that indicates if a doc was actually sent to the customer and with that, is valid.

**Comment by dragotin** [comment]
I think this specific issue can be closed. Reopen just in case not...
