### ISSUE TITLE
Follow-up document: data in header and footer are not taken over

### ISSUE THREAD

**Issue by rzlbrmft** [dragotin/kraft#91]
While creating a Follow-up document (Nachfolgedokument) with Ctrl+F (Strg+F) the data in header area (Kopfbereich) and footer area (Fußbereich) are not taken over from the predecessor.

**Comment by dragotin** [comment]
Which version are you using? This was fixed in Version 0.90: https://volle-kraft-voraus.de/Main/Changelog090 first line.

Please reopen if it still does not work for you.

**Comment by rzlbrmft** [comment]
I use Version 0.95

**Comment by rzlbrmft** [comment]
I use Version 0.95 - but I cannot reopen this issue.

**Comment by dragotin** [comment]
I will check again.

**Comment by dragotin** [comment]
I have investigated. The new document gets the standard text for footer and header of the target document type. 

For example: You create an invoice as follow up document of an offer. The new document gets the standard texts of the invoice, not just the text that the offer had. That is probably the best approach.

How is the standard text for a document type defined? Text templates for header and footer can be entered in the doc editor, when templates are on display. Just name one of the templates `standard` and that will be the default text for that doc type.

![ksnip_20201213-212438](https://user-images.githubusercontent.com/1070214/102022878-f549cb00-3d89-11eb-87de-7ba407f6163c.png)

**Comment by dragotin** [comment]
Added a patch that if the standard text of the new doc is empty, the text from the source document is used.
